---
name: Build Node
on:
  workflow_call:

jobs:
  compile:
    timeout-minutes: 10
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v5
        with:
          show-progress: false
      - uses: actions/setup-node@v6
        with:
          node-version: '22'
          cache: npm
      - run: npm ci
      - run: npm run compile
  lint:
    timeout-minutes: 5
    if: ${{ needs.compile.result == 'success' }}
    runs-on: ubuntu-24.04
    needs: [compile]
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v5
        with:
          show-progress: false
          fetch-depth: 0
      - uses: actions/setup-node@v6
        with:
          node-version: '22'
          cache: npm
      - run: npm ci
      - run: npm run lint
  test:
    timeout-minutes: 10
    if: ${{ needs.compile.result == 'success' }}
    needs: [compile]
    runs-on: 'ubuntu-24.04'
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v5
        with:
          show-progress: false
      - uses: actions/setup-node@v6
        with:
          node-version: '22'
          cache: npm
      - run: npm ci
      - run: npm test
