---
name: Build and release

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  release:
    types:
      - published

permissions:
  contents: read
  id-token: write

jobs:
  build:
    if: ${{ github.event_name == 'push' }}
    uses: ./.github/workflows/build.yml
    secrets: inherit

  publish:
    if: ${{ github.event_name == 'release' }}
    uses: ./.github/workflows/publish.yml
    with:
      pre_release: ${{ github.event.release.prerelease }}
    secrets: inherit
